repository: ${GITHUB_REPOSITORY}/${OCTOCOV_OS}

coverage:
  paths:
    - ${OCTOCOV_COVERAGE_PATH}

testExecutionTime:
  if: false

comment:
  if: is_pull_request && github.event.pull_request.head.repo.full_name == env.GITHUB_REPOSITORY
  updatePrevious: true
  hideFooterLink: false

summary:
  if: true
  hideFooterLink: false
