autoInstallPeers: true

engineStrict: true

minimumReleaseAge: 1440

nodeLinker: hoisted

packageManagerStrict: true

strictPeerDependencies: true

verifyDepsBeforeRun: false

allowBuilds:
  '@vscode/vsce-sign': true
  keytar: true
  lefthook: true
  puppeteer: false
  sharp: true
  tldjs: false
