import type { SplitPdfLabels } from '@lgh-split-pdf-protocol';

export const defaultLabels: SplitPdfLabels = {
  title: 'Split PDF',
  description: 'Select pages and assign an output name to each group.',
  preview: 'Preview',
  previewDescription: 'Preview the selected pages.',
  previewAriaLabel: 'PDF preview',
  groups: 'Groups',
  pages: 'Pages',
  pagesPlaceholder: 'Example: 1, 3-6, 10-',
  outputName: 'Output name',
  outputNamePlaceholder: 'group-1',
  outputPath: 'Output path',
  addGroup: 'Add group',
  removeGroup: 'Remove group',
  apply: 'Apply',
  cancel: 'Cancel',
  previewRenderError: 'Could not display the PDF',
  previewApplyError: 'PDF preview must render before applying.',
  pagesRequiredError: 'At least one page must be selected.',
  pageWholeNumberError: 'Page must be a whole number: {0}',
  pageOutOfRangeError: 'Selected page is out of range: {0}',
  allPages: 'All pages',
  focusedPages: 'Focused',
  zoom: 'Preview zoom',
  dragGroup: 'Drag group',
  moveUp: 'Move up',
  moveDown: 'Move down',
  outputOrder: 'Output order',
  invalidPages: 'Invalid page expression: {0}',
  descendingPages: 'Page range must ascend: {0}',
  outputNameEmpty: 'Output name cannot be empty.',
  outputNamePath: 'Output name must not contain path separators or .. .',
  outputNameDuplicate: 'Output name is duplicated: {0}',
};
