name: Check

on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: check-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - uses: pnpm/action-setup@v4
              with:
                  version: 11.8.0

            - uses: actions/setup-node@v6
              with:
                  node-version: '22'
                  cache: pnpm

            - run: pnpm install --frozen-lockfile
              shell: bash

            - run: pnpm run lint
              shell: bash

            - run: pnpm run typecheck
              shell: bash
