name: Check

on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: check-${{ github.ref }}
    cancel-in-progress: true

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - uses: actions/setup-node@v6
              with:
                  node-version: '22.22.2'
                  package-manager-cache: false

            - run: npm install -g npm@12.0.1
              shell: bash

            - run: node --version && npm --version
              shell: bash

            - run: npm ci
              shell: bash

            - run: npm run check
              shell: bash
